apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
  labels:
    app: train-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-service
  template:
    metadata:
      labels:
        app: train-service
    spec:
      containers:
        - name: train-service
          image: rwdnas1/train-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@host.minikube.internal:5434/train_db"
            - name: REDIS_HOST
              value: "host.minikube.internal"
            - name: REDIS_PORT
              value: "6379"
            # - name: LOGSTASH_HOST
            #   value: "host.docker.internal"
            # - name: LOGSTASH_PORT
            #   value: "5044" 

---
apiVersion: v1
kind: Service
metadata:
  name: train-service
spec:
  type: ClusterIP
  selector:
    app: train-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
